name: like_point
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  get: ^4.7.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/rank/
    - assets/role/
    - assets/rune/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/IconApp.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/IconApp.png"
  android: true
  ios: false
  android_12:
    color: "#CAA1FF"
    image: "assets/icon/IconApp.png"
